const data = [
    {
      id: 1,
      name: "현오",
      nickname: "박현오 | 가수",
      img: "hyuno.jpg",
      birth: "1999. 3. 19",
      album: ["hyuno1.jpg", 
              "hyuno2.jpg",
              "hyuno3.jpg",
              "hyuno4.jpg",
              "hyuno5.jpg"],
      info: ["Are you ready? | 2019. 12. 02",
              "Promise U | 2020. 01. 15",
              "Pierrot | 2020. 05. 22",
              "이별을 배웠어 | 2023. 11. 27"]
    },
    {
      id: 2,
      name: "Leo",
      nickname: "고규락, 리오 | 가수, 음악프로듀서",
      img: "leo.jpg",
      birth: "1997. 7. 31",
      album: ["leo1.jpg",
              "leo2.jpg",
              "leo3.jpg",
              "leo4.jpg",
              "leo5.jpg",
              "leo6.jpg",
              "leo7.jpg",
              "leo8.jpg"]
    },
    {
      id: 3,
      name: "KOYO",
      nickname: "이윤진, 코요 | 가수",
      img: "koyo.jpg",
      birth: "1994. 10. 7",
      album: ["koyo1.jpg",
              "koyo2.jpg",
              "koyo3.jpg",
              "koyo4.jpg",
              "koyo5.jpg",
              "koyo6.jpg",
              "koyo7.jpg",
              "koyo8.jpg",
              "koyo9.jpg",
              "koyo10.jpg",
              "koyo11.jpg",
              "koyo12.jpg",
              "koyo13.jpg",
              "koyo14.jpg",]
    },
    {
      id: 4,
      name: "Sufia",
      nickname: "장혜지 | 가수",
      img: "sufia.jpg",
      album: ["sufia1.jpg",
              "sufia2.jpg",
              "sufia3.jpg",
              "sufia4.jpg",
              "sufia5.jpg"]
    },
    {
      id: 5,
      name: "김지현",
      nickname: "공상 | 가수",
      img: "jihyun.jpg",
      album: ["gong1.jpg",
              "gong2.jpg",
              "gong3.jpg",
              "gong4.jpg",
              "gong5.jpg",
              "gong6.jpg",
              "gong7.jpg",
              "gong8.jpg",]
    },
    {
        id: 6,
        name: "곽소영",
        nickname: "공상 | 피아노연주가",
        img: "soyoung.jpg",
        album: ["gong1.jpg",
                "gong2.jpg",
                "gong3.jpg",
                "gong4.jpg",
                "gong5.jpg",
                "gong6.jpg",
                "gong7.jpg",
                "gong8.jpg",]
    },
    {
        id: 7,
        name: "JuwON",
        nickname: "박주원 | 가수",
        img: "juwon.jpg",
        birth: "1998. 5. 22",
        album: ["juwon1.jpg",
              "juwon2.jpg",
              "juwon3.jpg",
              "juwon4.jpg",
              "juwon5.jpg",
              "juwon6.jpg"]
    },
  ];
  
  export default data;